# Generated by Django 3.0.5 on 2020-05-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200429_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(),
        ),
    ]
