# Generated by Django 3.0.5 on 2020-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200509_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
