# Generated by Django 3.0.5 on 2020-05-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200509_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='date_created',
            new_name='datetime',
        ),
    ]
