# Generated by Django 3.0.5 on 2020-05-09 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200509_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='datetime',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='publish',
            field=models.DateField(default=datetime.datetime(2020, 5, 9, 9, 41, 23, 758707, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
