# Generated by Django 3.0.5 on 2020-05-09 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200509_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='publish',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
