# Generated by Django 3.0.5 on 2020-05-09 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_contactmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='time',
            field=models.DateField(default=datetime.time, verbose_name='Time'),
        ),
    ]
